name: Run Gradle Build

on:
  push:
    paths:
      - src/**
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 10

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            **/loom-cache
            **/prebundled-jars
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload built mod JAR
        uses: actions/upload-artifact@v4.3.0
        with:
          name: mod-jar
          path: build/libs/*.jar
